### ISSUE TITLE
dkms support

### ISSUE THREAD

**Issue by wommy** [brunokc/pve-kernel-builder#1]
howdy!

this project saved my butt, so im here tryna help

i was wondering if youve heard of DKMS?

- https://en.wikipedia.org/wiki/Dynamic_Kernel_Module_Support
- https://github.com/dell/dkms
- https://www.kernel.org/doc/ols/2004/ols2004v1-pages-187-202.pdf
- https://wiki.debian.org/KernelDKMS
- https://wiki.archlinux.org/title/Dynamic_Kernel_Module_Support
- https://wiki.archlinux.org/title/DKMS_package_guidelines

i originally heard about it a few years ago when i had an old imac that needed a [broadcom driver](https://archlinux.org/packages/extra/x86_64/broadcom-wl-dkms/) for the wifi card
everytime i got a kernel update, i lost wifi, it was the worst, 
had to lug the computer upstairs, hard wire it to patch it for the update,
i literally didnt even understand why it was breaking for 6 months probably
when i found the dkms patch, it solved my issue: no more rebuilding, it just auto applied this patch
i cant believe it just wasnt that easy 

i currently use it with my proxmox build to get the [nvidia drivers](https://wiki.debian.org/NvidiaGraphicsDrivers#Debian_12_.22Bookworm.22)

you, me, and many others have this exact same problem
i feel like the DKMS path might solve this problem with less labor, while benefitting a wider community 
i dont need to tell you anything beats rebuilding the kernel over and over
if done right, i think it can be used across the distros: debian arch fedora

all that being said, ive only used it, ive never built for it
but from my experience, this was the first thing i looked for,
i was slightly surprised there already wasnt a fix

i see the amount of work youre putting in and i can afford to pick up a shovel myself right now
might as well get as close to solving it for everyone as possible 
i appreciate all your hard work 🙏
lmk if theres anything i can do!

ps:
i know this is alpha software, but im not the most familiar with docker nor github actions
for the life of me, i cant figure out what commands youre using to run what
at very least the docs will improve!

**Comment by brunokc** [comment]
Hey!

Thanks for reaching out! Glad to hear that this was useful to someone. 

I have heard of DKMS and read about it a while ago. Unfortunately, based on my reading of [this explanation here](https://github.com/kiler129/relax-intel-rmrr/blob/master/deep-dive.md#why-kernel-patch-and-not-a-loadable-module) by kiler129, I don't think a module with the relaxable RMRRs functionality is feasible.

Having said that, I agree kernel rebuilds are no fun. That's why I'm trying to make this as automated as I can. The idea is for GitHub to do everything for me, including checking for new pve kernel releases and automatically patch, build and release them. That's what I'm concentrating on at the moment. 

I'm also trying to make this as generic as possible, so if other patches are needed, it's easy to just drop them in.

I'm using docker as a way for me to get the right build environment set up and isolate the build and its dependencies. I haven't been able to use the ubuntu-22.04 image on GitHub to build the kernel so I'm now building it on a Debian 11 container. That worked much better (even though Proxmox's kernel is derived from the Ubuntu kernel). 

The GitHub actions are here just to automate things for me. They are not necessary for you to build it on your own (just clone the repo and run build.sh). I'm using them to automate things for me. First time doing it so it's going slow and the debugging story hasn't been great. The [workflow documentation](https://docs.github.com/en/actions/using-workflows/about-workflows) is what got me started.

Let me know if there's anything that's not making sense to you and I'll try to explain.

Thanks!
